In [1]:
import IPython
import json
# Numpy is a library for working with Arrays
import numpy as np
# SciPy implements many different numerical algorithms
import scipy as sp
# Pandas is good with data tables
import pandas as pd
# Module for plotting
import matplotlib
#BeautifulSoup parses HTML documents (once you get them via requests)
import bs4
# Nltk helps with some natural language tasks, like stemming
import nltk
# Bson is a binary format of json to be stored in databases
import bson
# Mongo is one of common nosql databases 
# it stores/searches json documents natively
import pymongo
print ("IPython version:      %6.6s", IPython.__version__)

IPython version:      %6.6s 6.1.0


In [2]:
#Here is what numpy can do\n",
print ("Make a 2 row x 3 column array of random numbers")
x = np.random.random((2, 3))
print (x)

#array operation (as in R)
print ("Add 5 to every element")
x = x + 5
print (x)

# get a slice (first row) (as in R)
print ("Get the first row")
print (x[0, :])

Make a 2 row x 3 column array of random numbers
[[ 0.20354485  0.87353642  0.79226415]
 [ 0.26457656  0.23486214  0.8240387 ]]
Add 5 to every element
[[ 5.20354485  5.87353642  5.79226415]
 [ 5.26457656  5.23486214  5.8240387 ]]
Get the first row
[ 5.20354485  5.87353642  5.79226415]


In [3]:
# IPython is quite modern: just press <TAB> at the end of the unfinished statement to see the documentation
#       on possible completions.
#       In the code cell below, type x.<TAB>, to find built-in operations for x
x.any

<function ndarray.any>

In [2]:
%matplotlib inline 
import matplotlib.pyplot as plt
heads = np.random.binomial(500, .5, size=500)
histogram = plt.hist(heads, bins=10)

NameError: name 'np' is not defined

# Task 1
## write a program to produce Fibonacci numbers up to 1000000

In [3]:
def Fib():
    n1, n2 = 0, 1
    
    while True:
        if n1 > 1000000:
            break
        
        print(n1)
        next = n1 + n2

        n1 = n2
        n2 = next

Fib()

0
1
1
2
3
5
8
13
21
34
55
89
144
233
377
610
987
1597
2584
4181
6765
10946
17711
28657
46368
75025
121393
196418
317811
514229
832040


# Task 2
## write a program to simulate 1000 tosses of a fair coin (use np.random.binomial)
## Calculate the mean and standard deviation of that sample

In [1]:
test = np.random.binomial(1000,0.5,1)
print(test)

ERROR: Error in np.random.binomial(1000, 0.5, 1): could not find function "np.random.binomial"


# Task 3
## Produce a scatterplot of y = 0.5*x+e where x has gaussian (0, 5) and e has gaussian (0, 1) distributions 
### use numpy.random.normal to generate gaussian distribution